# Generated by Django 5.0 on 2025-02-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=3800, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ugx_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
