# Generated by Django 5.0 on 2025-02-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_exchange_rate_userprofile_ugx_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='exchange_rate',
        ),
    ]
