# Generated by Django 5.0 on 2025-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_active',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_deposited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(choices=[('bronze', 'Bronze Member'), ('silver', 'Silver Member'), ('gold', 'Gold Member'), ('platinum', 'Platinum Admin')], default='bronze', max_length=20),
        ),
    ]
