# Generated by Django 5.0 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_days_active_userprofile_days_deposited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(choices=[('bronze', 'Bronze Member'), ('silver', 'Silver Member'), ('gold', 'Gold Member'), ('platinum', 'Platinum Admin')], default='none', max_length=20),
        ),
    ]
