# Generated by Django 5.0 on 2025-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(choices=[('none', 'No Badge'), ('bronze', 'Bronze Member'), ('silver', 'Silver Member'), ('gold', 'Gold Member'), ('platinum', 'Platinum Admin')], default='none', max_length=20),
        ),
    ]
