# Generated by Django 5.1.6 on 2025-02-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deposit_days', models.PositiveIntegerField(default=0)),
                ('days_on_network', models.PositiveIntegerField(default=0)),
                ('last_deposit_date', models.DateField(blank=True, null=True)),
                ('current_badge', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
