# Generated by Django 5.0 on 2025-02-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
