# Generated by Django 5.0 on 2025-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_retweet',
            field=models.BooleanField(default=False),
        ),
    ]
