# Generated by Django 5.0 on 2025-02-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_tweet_is_retweet_tweet_retweet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
