# Generated by Django 5.0 on 2025-02-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='community.tweet'),
        ),
    ]
