# Generated by Django 5.0 on 2025-03-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_tweet_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_thread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='community.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='thread_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
