# Generated by Django 5.0 on 2025-02-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_transaction_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hashed_detail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
